import Foundation

public enum ContentScopeScriptsResources {
    public static var bundle: Bundle {
        // Bundle.module is only available when the target has resources
        // Since resources are in build/apple/ which may not exist during development,
        // we provide a fallback
        
        // Try to find the module bundle (available when resources exist and are built)
        // This will be generated by SPM when resources are present
        #if SWIFT_PACKAGE
        // When built as a Swift package with resources, Bundle.module is available
        // But if resources don't exist, we need a fallback
        if let moduleBundle = Bundle(identifier: "com.duckduckgo.content-scope-scripts.ContentScopeScriptsResources") {
            return moduleBundle
        }
        #endif
        
        // Fallback: try to find bundle by path
        // Look for the bundle in common locations
        let possiblePaths = [
            Bundle.main.resourcePath,
            Bundle.main.bundlePath,
        ]
        
        for path in possiblePaths.compactMap({ $0 }) {
            if let bundle = Bundle(path: path) {
                return bundle
            }
        }
        
        // Final fallback: main bundle
        return Bundle.main
    }
}
