export const oldVariants = {
    bringStuff: {
        id: 'bring-stuff',
        icon: 'Bring-Stuff',
        titleText: 'Bring your stuff',
        descriptionText: 'Import bookmarks, favorites, and passwords for a smooth transition from your old browser.',
        action: () => {},
        actionText: 'Import Now',
        confirmationText: 'Imported!',
    },
    defaultApp: {
        id: 'defaultApp',
        icon: 'Default-App',
        titleText: 'Set as Default Browser',
        descriptionText: 'We automatically block trackers as you browse. It’s privacy, simplified.',
        action: () => {},
        actionText: 'Make Default Browser',
        confirmationText: 'Done',
    },
    blockCookies: {
        id: 'blockCookies',
        icon: 'Cookie-Pops',
        titleText: 'Block Cookie Pop-ups',
        descriptionText: 'We need your permission to say no to cookies on your behalf. Easy choice.',
        action: () => {},
        actionText: 'Block Cookie Pop-ups',
        confirmationText: 'Done',
    },
    emailProtection: {
        id: 'emailProtection',
        icon: 'Email-Protection',
        titleText: 'Protect Your Inbox',
        descriptionText: 'Generate @duck.com addresses that remove trackers from email and forwards to your inbox.',
        action: () => {},
        actionText: 'Get Email Protection',
        confirmationText: 'Done',
    },
    duckPlayer: {
        id: 'duckplayer',
        icon: 'Tube-Clean',
        titleText: 'YouTube Without Creepy Ads',
        descriptionText: 'Enjoy a clean viewing experience without personalized ads.',
        action: () => {},
        actionText: 'Try DuckPlayer',
        confirmationText: 'Imported!',
    },
    addAppDockMac: {
        id: 'addAppToDockMac',
        icon: 'Dock-Add-Mac',
        titleText: 'Add App to the Dock',
        descriptionText: 'Access DuckDuckGo faster by adding it to the Dock.',
        action: () => {},
        actionText: 'Add to Dock',
        confirmationText: 'Added to your Dock!',
    },
    pinAppToTaskbar: {
        id: 'pinAppToTaskbar',
        icon: 'Dock-Add-Windows',
        titleText: 'Pin App to the Taskbar',
        description: 'Access DuckDuckGo faster by pinning it to the Taskbar.',
        action: () => {},
        actionText: 'Pin to Taskbar',
        confirmationText: 'Pinned to Taskbar', // this is only available >= Windows 11 users
    },
};
