/**
 * Map of feature names to feature classes.
 *
 * New features must be added to this map.
 *
 * @typedef {{
 *   apiManipulation: import('./features/api-manipulation').default,
 *   autofillImport: import('./features/autofill-import').default,
 *   breakageReporting: import('./features/breakage-reporting').default,
 *   brokerProtection: import('./features/broker-protection').default,
 *   clickToLoad: import('./features/click-to-load').default,
 *   cookie: import('./features/cookie').default,
 *   duckAiDataClearing: import('./features/duck-ai-data-clearing').default,
 *   duckPlayer: import('./features/duck-player').default,
 *   duckPlayerNative: import('./features/duck-player-native').default,
 *   elementHiding: import('./features/element-hiding').default,
 *   exceptionHandler: import('./features/exception-handler').default,
 *   favicon: import('./features/favicon').default,
 *   fingerprintingAudio: import('./features/fingerprinting-audio').default,
 *   fingerprintingBattery: import('./features/fingerprinting-battery').default,
 *   fingerprintingCanvas: import('./features/fingerprinting-canvas').default,
 *   fingerprintingHardware: import('./features/fingerprinting-hardware').default,
 *   fingerprintingScreenSize: import('./features/fingerprinting-screen-size').default,
 *   fingerprintingTemporaryStorage: import('./features/fingerprinting-temporary-storage').default,
 *   googleRejected: import('./features/google-rejected').default,
 *   gpc: import('./features/gpc').default,
 *   harmfulApis: import('./features/harmful-apis').default,
 *   messageBridge: import('./features/message-bridge').default,
 *   navigatorInterface: import('./features/navigator-interface').default,
 *   pageContext: import('./features/page-context').default,
 *   performanceMetrics: import('./features/performance-metrics').default,
 *   referrer: import('./features/referrer').default,
 *   uaChBrands: import('./features/ua-ch-brands').default,
 *   webCompat: import('./features/web-compat').default,
 *   webInterferenceDetection: import('./features/web-interference-detection').default,
 *   webTelemetry: import('./features/web-telemetry').default,
 *   windowsPermissionUsage: import('./features/windows-permission-usage').default,
 * }} FeatureMap
 */

/** @typedef {keyof FeatureMap} FeatureName */

// Features must exist in either `baseFeatures` or `otherFeatures`
export const baseFeatures = /** @type {FeatureName[]} */ ([
    'fingerprintingAudio',
    'fingerprintingBattery',
    'fingerprintingCanvas',
    'googleRejected',
    'gpc',
    'fingerprintingHardware',
    'referrer',
    'fingerprintingScreenSize',
    'fingerprintingTemporaryStorage',
    'navigatorInterface',
    'elementHiding',
    'exceptionHandler',
    'apiManipulation',
]);

const otherFeatures = /** @type {FeatureName[]} */ ([
    'clickToLoad',
    'cookie',
    'messageBridge',
    'duckPlayer',
    'duckPlayerNative',
    'duckAiDataClearing',
    'duckAiChatHistory',
    'harmfulApis',
    'webCompat',
    'webInterferenceDetection',
    'windowsPermissionUsage',
    'uaChBrands',
    'brokerProtection',
    'performanceMetrics',
    'breakageReporting',
    'autofillImport',
    'favicon',
    'webTelemetry',
    'pageContext',
]);

/** @type {Record<string, FeatureName[]>} */
export const platformSupport = {
    apple: ['webCompat', 'duckPlayerNative', ...baseFeatures, 'webInterferenceDetection', 'pageContext'],
    'apple-isolated': [
        'duckPlayer',
        'duckPlayerNative',
        'brokerProtection',
        'breakageReporting',
        'performanceMetrics',
        'clickToLoad',
        'messageBridge',
        'favicon',
    ],
    'apple-ai-clear': ['duckAiDataClearing'],
    'apple-ai-history': ['duckAiChatHistory'],
    android: [...baseFeatures, 'webCompat', 'webInterferenceDetection', 'breakageReporting', 'duckPlayer', 'messageBridge'],
    'android-broker-protection': ['brokerProtection'],
    'android-autofill-import': ['autofillImport'],
    'android-adsjs': [
        'apiManipulation',
        'webCompat',
        'fingerprintingHardware',
        'fingerprintingScreenSize',
        'fingerprintingTemporaryStorage',
        'fingerprintingAudio',
        'fingerprintingBattery',
        'gpc',
        'breakageReporting',
    ],
    windows: [
        'cookie',
        ...baseFeatures,
        'webInterferenceDetection',
        'webTelemetry',
        'windowsPermissionUsage',
        'uaChBrands',
        'duckPlayer',
        'brokerProtection',
        'breakageReporting',
        'messageBridge',
        'webCompat',
        'pageContext',
        'duckAiDataClearing',
        'duckAiChatHistory',
    ],
    firefox: ['cookie', ...baseFeatures, 'clickToLoad', 'webInterferenceDetection', 'breakageReporting'],
    chrome: ['cookie', ...baseFeatures, 'clickToLoad', 'webInterferenceDetection', 'breakageReporting'],
    'chrome-mv3': ['cookie', ...baseFeatures, 'clickToLoad', 'webInterferenceDetection', 'breakageReporting'],
    integration: [...baseFeatures, ...otherFeatures],
};
