// Features must exist in either `baseFeatures` or `otherFeatures`
export const baseFeatures = /** @type {const} */ ([
    'fingerprintingAudio',
    'fingerprintingBattery',
    'fingerprintingCanvas',
    'googleRejected',
    'gpc',
    'fingerprintingHardware',
    'referrer',
    'fingerprintingScreenSize',
    'fingerprintingTemporaryStorage',
    'navigatorInterface',
    'elementHiding',
    'exceptionHandler',
    'apiManipulation',
]);

const otherFeatures = /** @type {const} */ ([
    'clickToLoad',
    'cookie',
    'messageBridge',
    'duckPlayer',
    'duckPlayerNative',
    'duckAiListener',
    'harmfulApis',
    'webCompat',
    'windowsPermissionUsage',
    'brokerProtection',
    'performanceMetrics',
    'breakageReporting',
    'autofillImport',
    'favicon',
    'webTelemetry',
    'pageContext',
    'youtubeAdDetector',
]);

/** @typedef {baseFeatures[number]|otherFeatures[number]} FeatureName */
/** @type {Record<string, FeatureName[]>} */
export const platformSupport = {
    apple: ['webCompat', 'duckPlayerNative', ...baseFeatures, 'duckAiListener', 'pageContext'],
    'apple-isolated': [
        'duckPlayer',
        'duckPlayerNative',
        'brokerProtection',
        'performanceMetrics',
        'clickToLoad',
        'messageBridge',
        'favicon',
    ],
    android: [...baseFeatures, 'webCompat', 'breakageReporting', 'duckPlayer', 'messageBridge'],
    'android-broker-protection': ['brokerProtection'],
    'android-autofill-import': ['autofillImport'],
    'android-adsjs': [
        'apiManipulation',
        'webCompat',
        'fingerprintingHardware',
        'fingerprintingScreenSize',
        'fingerprintingTemporaryStorage',
        'fingerprintingAudio',
        'fingerprintingBattery',
        'gpc',
        'breakageReporting',
    ],
    windows: [
        'cookie',
        ...baseFeatures,
        'webTelemetry',
        'windowsPermissionUsage',
        'duckPlayer',
        'brokerProtection',
        'breakageReporting',
        'messageBridge',
        'webCompat',
        'pageContext',
        'duckAiListener',
    ],
    firefox: ['cookie', ...baseFeatures, 'clickToLoad', 'youtubeAdDetector'],
    chrome: ['cookie', ...baseFeatures, 'clickToLoad'],
    'chrome-mv3': ['cookie', ...baseFeatures, 'clickToLoad'],
    integration: [...baseFeatures, ...otherFeatures],
};
