name: Release

#... on push after PR

jobs:
  release_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Build release
        run: |
          npm install
          npm run build

      - name: Check in files
        run: |
          git add -f build/ Sources/

      - name: Commit build files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Release staging build [ci release]"
          --create-branch
          branch: "releases-${....}" # numbered by PR number

## add comment to PR about link?

## separate workflow on pr merge delete release branch?
